classInst(alice, student).
classInst(bob, professor).
classInst(logic101, course).
roleInst(alice, logic101, enrolledIn).
roleInst(bob, logic101, teaches).
roleInst(charlie, logic101, enrolledIn).
subClass(student, person).
subClass(professor, person).
subRole(teaches, memberOf).
subRole(enrolledIn, memberOf).
domain(person, memberOf).
domain(professor, teaches).
domain(student, enrolledIn).
range(course, memberOf).
range(course, teaches).
range(course, enrolledIn).
inverse(hasStudent, enrolledIn).
inverse(enrolledIn, hasStudent).
classWit(w_course, course).
classInst(w_course, course).
witness(w_course).
classWit(w_person, person).
classInst(w_person, person).
witness(w_person).
classWit(w_professor, professor).
classInst(w_professor, professor).
witness(w_professor).
classWit(w_student, student).
classInst(w_student, student).
witness(w_student).
subjWit(ws_enrolledIn, enrolledIn).
objWit(wo_enrolledIn, enrolledIn).
witness(ws_enrolledIn).
witness(wo_enrolledIn).
roleWit(ws_enrolledIn, wo_enrolledIn, enrolledIn).
roleInst(ws_enrolledIn, wo_enrolledIn, enrolledIn).
subjWit(ws_hasStudent, hasStudent).
objWit(wo_hasStudent, hasStudent).
witness(ws_hasStudent).
witness(wo_hasStudent).
roleWit(ws_hasStudent, wo_hasStudent, hasStudent).
roleInst(ws_hasStudent, wo_hasStudent, hasStudent).
subjWit(ws_memberOf, memberOf).
objWit(wo_memberOf, memberOf).
witness(ws_memberOf).
witness(wo_memberOf).
roleWit(ws_memberOf, wo_memberOf, memberOf).
roleInst(ws_memberOf, wo_memberOf, memberOf).
subjWit(ws_teaches, teaches).
objWit(wo_teaches, teaches).
witness(ws_teaches).
witness(wo_teaches).
roleWit(ws_teaches, wo_teaches, teaches).
roleInst(ws_teaches, wo_teaches, teaches).

classInst(E, B) :- classInst(E, A), subClass(A, B).
classInst(E1, A) :- roleInst(E1, E2, R), domain(W, R), subClass(W, A).
classInst(E2, A) :- roleInst(E1, E2, R), inverse(S, R), domain(W, S), subClass(W, A).
roleInst(E1, E2, S) :- roleInst(E1, E2, R), subRole(R, S).
roleInst(E2, E1, S) :- roleInst(E1, E2, R), inverse(R1, R), subRole(R1, S).
roleInst(E2, E1, S) :- roleInst(E1, E2, R), inverse(S1, S), subRole(R, S1).
roleInst(E1, E2, S) :- roleInst(E1, E2, R), subRole(R1, S1), inverse(R1, R), inverse(S1, S).
subClass(A, B) :- classWit(E, A), classInst(E, B).
subClass(W, A) :- domain(W, R), subjWit(E, R), classInst(E, A).
subClass(W, A) :- inverse(R, S), domain(W, S), objWit(E, R), classInst(E, A).
subRole(R, S) :- subjWit(E1, R), objWit(E2, R), roleInst(E1, E2, S).
subRole(R, S1) :- inverse(S1, S), subjWit(E1, R), objWit(E2, R), roleInst(E2, E1, S).
subRole(R1, S) :- inverse(R1, R), subjWit(E1, R), objWit(E2, R), roleInst(E2, E1, S).
subRole(R1, S1) :- inverse(R1, R), inverse(S1, S), subjWit(E1, R), objWit(E2, R), roleInst(E1, E2, S).
query_result(X) :- classInst(X, student).
query_result(X) :- classInst(X, professor).
